name: Deploy Spring Boot to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            echo "===== START DEPLOY ====="
            
            cd ~/lms || exit 1
            
            echo "===== PULL NEW CODE ====="
            git pull origin main
            
            echo "===== STOP OLD CONTAINERS ====="
            docker-compose -f docker-compose.prod.yml down
            
            echo "===== BUILD + START NEW CONTAINERS ====="
            docker-compose -f docker-compose.prod.yml up -d --build
            
            echo "===== CLEAN UNUSED IMAGES ====="
            docker image prune -f
            
            echo "===== CHECK RUNNING CONTAINERS ====="
            docker ps
            
            echo "===== DEPLOY DONE ====="
